export const SET_USERS = "SET_USERS",
	SET_AUTH = "SET_AUTH",
	SET_CURRENT_USER = "SET_CURRENT_USER",
	SET_CURRENT_USER_ID = "SET_CURRENT_USER_ID",
	SET_TOKEN = "SET_TOKEN",
	SET_REGISTRATION_SUCCESS = 'SET_REGISTRATION_SUCCESS',
	SET_REGISTRATION_ERROR = 'SET_REGISTRATION_ERROR',
	SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';